Repository IntelliFire-UofG/IntelliFireCore, pull requests merged in 2025-03, with the labels that each got.

#50 ADS Driver adaptation to UI
  CMakeLists.txt
  include/ads1015rpi.h
  include/ads1115rpi.h
  src/IntelliFireUI/include/ads1115manager.h
  src/IntelliFireUI/include/keyLogger.h
  src/IntelliFireUI/include/mainwindow.h
  src/IntelliFireUI/include/sensorContainer.h
  src/IntelliFireUI/mainwindow.cpp
  src/IntelliFireUI/src/ads1115manager.cpp
  src/IntelliFireUI/src/keyLogger.cpp
  src/IntelliFireUI/src/sensorContainer.cpp
  src/ads1015rpi.cpp
  src/ads1115rpi.cpp
  tests/ADS1015/CMakeLists.txt
  tests/ADS1015/multipleChannelsADC.cpp
  tests/ADS1115/CMakeLists.txt
  tests/ADS1115/multipleChannelsADC.cpp
  tests/MultipleChannelsADC/multipleChannelsADC.cpp
Labels: enhancement

#54 Water Pump activation code
  CMakeLists.txt
  include/fireDetector.h
  include/pumpControl.h
  src/IntelliFireUI/include/ads1115manager.h
  src/IntelliFireUI/main.cpp
  src/IntelliFireUI/src/ads1115manager.cpp
  src/fireDetector.cpp
  src/pumpControl.cpp
Labels: enhancement

#55 Merge pull request #54 from IntelliFire-UofG/BrenDevelopmentBranch
  CMakeLists.txt
  include/fireDetector.h
  include/pumpControl.h
  src/IntelliFireUI/include/ads1115manager.h
  src/IntelliFireUI/include/mainwindow.h
  src/IntelliFireUI/main.cpp
  src/IntelliFireUI/mainwindow.cpp
  src/IntelliFireUI/src/ads1115manager.cpp
  src/fireDetector.cpp
  src/pumpControl.cpp
Labels: bug, enhancement

#57 Pump Indicator working in UI
  CMakeLists.txt
  include/pumpControl.h
  src/IntelliFireUI/include/mainwindow.h
  src/IntelliFireUI/main.cpp
  src/IntelliFireUI/mainwindow.cpp
  src/pumpControl.cpp
Labels: enhancement

#58 Pump Action Indicator
  CMakeLists.txt
  README.md
  include/pumpControl.h
  src/IntelliFireUI/include/mainwindow.h
  src/IntelliFireUI/main.cpp
  src/IntelliFireUI/mainwindow.cpp
  src/pumpControl.cpp
Labels: good first issue, improvement

#41 Check the new version of motor control
  CMakeLists.txt
  include/LN298MotorControlV2.h
  include/LN298MotorControlV3.h
  include/basicMotionV2.h
  src/LN298MotorControlV2.cpp
  src/LN298MotorControlV3.cpp
  src/basicMotionV2.cpp
  src/basicMotionV3.cpp
  src/main.cpp
Labels: bug, enhancement, help wanted
