Repository IntelliFire-UofG/IntelliFireCore, pull requests merged in 2025-02, with the labels that each got.

#5 1st Proposal for Project Structure
  CMakeLists.txt
  include/LM393FlameSensor.h
  include/LN298MotorControl.h
  include/eventHandler.h
  include/pumpControl.h
  src/LM393FlameSensor.cpp
  src/LN298MotorControl.cpp
  src/eventHandler.cpp
  src/main.cpp
  src/pumpControl.cpp
  tests/testMotor.cpp
  tests/testPump.cpp
  tests/testSensor.cpp
Labels: documentation, enhancement, good first issue

#6 Added GUI Dir to the structure
  src/GUI/mainwindow.cpp
Labels: enhancement

#11 Motor-v0
  tests/testMotor.cpp
Labels: enhancement

#20 Revert "Fixed issues in the header files and added basic logic for th…
  .DS_Store
  include/.DS_Store
  include/LN298MotorControl.h
  include/basicMotion.h
  src/LN298MotorControl.cpp
  src/basicMotion.cpp
  src/main.cpp
Labels: invalid

#21 Fixed issues where sensor UI wasn't loading images
  src/IntelliFireUI/CMakeLists.txt
  src/IntelliFireUI/resources.qrc
  src/IntelliFireUI/sensorContainer.cpp
Labels: enhancement

#30 ShahBranch and IR Sensor
  CMakeLists.txt
  README_IRSensor.md
  include/IRSensor.h
  src/IRSensor.cpp
Labels: enhancement

#31 Ultrasonic Sensor and Unified CMakeLists.txt
  CMakeLists.txt
  README_IRSensor.md
  README_Sensors.md
  include/UltraSonicSensor.h
  src/UltraSonicSensor.cpp
  tests/testIRSensor.cpp
  tests/testUltraSonicSensor.cpp
Labels: documentation, enhancement

#32 ADS1115 Values Definition for UI and Distance Sensors Implementation
  src/IntelliFireUI/build/CMakeFiles/CMakeConfigureLog.yaml
  src/IntelliFireUI/build/CMakeFiles/IntelliFireUI.dir/IntelliFireUI_autogen/mocs_compilation.cpp.o
  src/IntelliFireUI/build/CMakeFiles/IntelliFireUI.dir/IntelliFireUI_autogen/mocs_compilation.cpp.o.d
  src/IntelliFireUI/build/CMakeFiles/IntelliFireUI.dir/compiler_depend.internal
  src/IntelliFireUI/build/CMakeFiles/IntelliFireUI.dir/compiler_depend.make
  src/IntelliFireUI/build/CMakeFiles/IntelliFireUI.dir/main.cpp.o.d
  src/IntelliFireUI/build/CMakeFiles/IntelliFireUI.dir/mainwindow.cpp.o
  src/IntelliFireUI/build/CMakeFiles/IntelliFireUI.dir/mainwindow.cpp.o.d
  src/IntelliFireUI/build/CMakeFiles/IntelliFireUI.dir/sensorContainer.cpp.o
  src/IntelliFireUI/build/CMakeFiles/IntelliFireUI.dir/sensorContainer.cpp.o.d
  src/IntelliFireUI/build/CMakeFiles/IntelliFireUI_autogen.dir/ParseCache.txt
  src/IntelliFireUI/build/IntelliFireUI
  src/IntelliFireUI/build/IntelliFireUI_autogen/EWIEGA46WW/moc_mainwindow.cpp.d
  src/IntelliFireUI/build/IntelliFireUI_autogen/EWIEGA46WW/moc_sensorContainer.cpp
  src/IntelliFireUI/build/IntelliFireUI_autogen/EWIEGA46WW/moc_sensorContainer.cpp.d
  src/IntelliFireUI/build/IntelliFireUI_autogen/deps
  src/IntelliFireUI/include/ads1115manager.h
  src/IntelliFireUI/main.cpp
  src/IntelliFireUI/mainwindow.cpp
  src/IntelliFireUI/sensorContainer.cpp
  src/IntelliFireUI/sensorContainer.h
  src/IntelliFireUI/src/ads1115manager.cpp
Labels: enhancement

#37 Merged all UI code with updated and working ultrasonic distance measurements
  src/IntelliFireUI/CMakeLists.txt
  src/IntelliFireUI/UltraSonicSensor.cpp
  src/IntelliFireUI/UltraSonicSensor.h
  src/IntelliFireUI/sensorContainer.cpp
  src/IntelliFireUI/sensorContainer.h
  src/IntelliFireUI/ultrasonicDistance.cpp
  src/IntelliFireUI/ultrasonicDistance.h
Labels: enhancement

#44 Latest mo branch
  CMakeLists.txt
  src/IntelliFireUI/include/libcam2opencv.h
  src/IntelliFireUI/include/mainwindow.h
  src/IntelliFireUI/include/sensorContainer.h
  src/IntelliFireUI/libcam2opencv.cpp
  src/IntelliFireUI/mainwindow.cpp
Labels: enhancement
